version: '3.8'

services:
  web:
    image: ghcr.io/koalixswitzerland/koalixcrm-dev-container:main
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - FIREBASE_CREDENTIALS_PATH=/usr/src/app/firebase-credentials.json
      - KOALIXCRM_DEBUG=True